# [[repos]]
# repo = "local"
# hooks = [
#     { 
#         id = "generate-third-party-html", 
#         name = "Update Third Party Licenses HTML", 
#         entry = "bash -c '[ -f about.hbs ] || cargo about init && cargo about generate about.hbs > third-party-licenses.html && git add third-party-licenses.html about.hbs about.toml'", 
#         language = "system", 
#         files = "(^|/)Cargo\\.(toml|lock)$", 
#         pass_filenames = false 
#     },

#     { 
#         id = "generate-sbom", 
#         name = "Update CycloneDX SBOM", 
#         entry = "bash -c 'cargo cyclonedx --format json && git add *.cdx.json'", 
#         language = "system", 
#         files = "(^|/)Cargo\\.(toml|lock)$", 
#         pass_filenames = false 
#     }
# ]