[[repos]]
repo = "local"
hooks = [
    {
        id = "generate-sbom",
        name = "Update CycloneDX SBOM",
        entry = "bash -c 'cargo cyclonedx --manifest-path app/Cargo.toml --format json --override-filename app.cdx && mv app/app.cdx.json app.cdx.json && git add app.cdx.json'",
        language = "system",
        files = "(^|/)(Cargo\\.(toml|lock)|go\\.(mod|sum))$",
        pass_filenames = false
    }
]
