use serde::Deserialize;
use std::collections::HashMap;
use std::env;
use std::fs;
use std::path::Path;

#[derive(Deserialize)]
struct Config {
    budgets: Category,
    finanzberichte: Category,
    vorpruefung: Category,
}

#[derive(Deserialize)]
struct Category {
    sheet_names: HashMap<String, String>,
}

fn main() {
    println!("cargo:rerun-if-changed=excel_constants.json");

    let json_content = fs::read_to_string("excel_constants.json").expect("Failed to read JSON");
    let config: Config = serde_json::from_str(&json_content).expect("Failed to parse JSON");

    let out_dir = env::var_os("OUT_DIR").unwrap();
    let dest_path = Path::new(&out_dir).join("generated_constants.rs");

    let mut out = String::new();

    out.push_str("// Code generated by build.rs. DO NOT EDIT.\n\n");

    // Helper closure to write out the Rust constants
    let mut write_category = |prefix: &str, map: &HashMap<String, String>| {
        let mut keys: Vec<_> = map.keys().collect();
        keys.sort();

        let mut array_elements = Vec::new();
        for k in &keys {
            let var_name = format!("{}_{}", prefix, k.to_uppercase());
            out.push_str(&format!(
                "pub const {}: &str = \"{}\";\n",
                var_name, map[*k]
            ));
            array_elements.push(var_name);
        }
        out.push_str(&format!(
            "pub const {}_SHEET_NAMES: &[&str] = &[{}];\n\n",
            prefix,
            array_elements.join(", ")
        ));
    };

    write_category("BUDGET", &config.budgets.sheet_names);
    write_category("FB", &config.finanzberichte.sheet_names);
    write_category("VP", &config.vorpruefung.sheet_names);

    fs::write(&dest_path, out).unwrap();
}
