// Code generated by go generate; DO NOT EDIT.
package constants

const (
	BudgetSheetDE = "Budget"
	BudgetSheetEN = "Budget"
	BudgetSheetES = "Presupuesto"
	BudgetSheetFR = "Budget"
	BudgetSheetPT = "Plano de custos e financiamento"
)

var BudgetSheetNames = []string{BudgetSheetDE, BudgetSheetEN, BudgetSheetES, BudgetSheetFR, BudgetSheetPT}

const (
	FBSheetDE = "Finanzbericht"
	FBSheetEN = "Financial Report"
	FBSheetES = "Informe financiero"
	FBSheetFR = "Rapport financier"
	FBSheetPT = "Relatório financeiro"
)

var FBSheetNames = []string{FBSheetDE, FBSheetEN, FBSheetES, FBSheetFR, FBSheetPT}

const (
	VPSheetAUSWERTUNG = "V. AUSWERTUNG"
	VPSheetBUDGET = "I. Budget"
	VPSheetDASHBOARD = "Dashboard"
	VPSheetDATEN = "Daten"
	VPSheetFINANZBERICHTE = "III. Finanzberichte"
	VPSheetKMW_MITTEL = "II. KMW-Mittel"
	VPSheetMA = "IV. MA"
)

var VPSheetNames = []string{VPSheetAUSWERTUNG, VPSheetBUDGET, VPSheetDASHBOARD, VPSheetDATEN, VPSheetFINANZBERICHTE, VPSheetKMW_MITTEL, VPSheetMA}

