//go:build ignore
// +build ignore

package main

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

type Category struct {
	SheetNames map[string]string `json:"sheet_names"`
}

type Config struct {
	Budgets        Category `json:"budgets"`
	Finanzberichte Category `json:"finanzberichte"`
	Vorpruefung    Category `json:"vorpruefung"`
}

func main() {
	jsonPath := filepath.Join("..", "..", "..", "core", "shared_constants", "excel_constants.json")
	data, err := os.ReadFile(jsonPath)
	if err != nil {
		panic(err)
	}

	var config Config
	if err := json.Unmarshal(data, &config); err != nil {
		panic(err)
	}

	out, err := os.Create("generated_constants.go")
	if err != nil {
		panic(err)
	}
	defer out.Close()

	fmt.Fprintln(out, "// Code generated by go generate; DO NOT EDIT.")
	fmt.Fprintln(out, "package constants")
	fmt.Fprintln(out)

	writeCategory(out, "Budget", config.Budgets.SheetNames)
	writeCategory(out, "FB", config.Finanzberichte.SheetNames)
	writeCategory(out, "VP", config.Vorpruefung.SheetNames)
}

func writeCategory(out *os.File, prefix string, m map[string]string) {
	var keys []string
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	fmt.Fprintln(out, "const (")
	var varNames []string
	for _, k := range keys {
		varName := fmt.Sprintf("%sSheet%s", prefix, strings.ToUpper(k))
		fmt.Fprintf(out, "\t%s = \"%s\"\n", varName, m[k])
		varNames = append(varNames, varName)
	}
	fmt.Fprintln(out, ")")
	fmt.Fprintln(out)

	fmt.Fprintf(out, "var %sSheetNames = []string{%s}\n\n", prefix, strings.Join(varNames, ", "))
}
